%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.17.0

-ifndef(shared).
-define(shared, true).

-define(shared_gpb_version, "4.17.0").

-ifndef('EVENT_STORE.CLIENT.SHARED.UUID.STRUCTURED_PB_H').
-define('EVENT_STORE.CLIENT.SHARED.UUID.STRUCTURED_PB_H', true).
-record('event_store.client.shared.UUID.Structured',
        {most_significant_bits = 0 :: integer() | undefined, % = 1, optional, 64 bits
         least_significant_bits = 0 :: integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.SHARED.UUID_PB_H').
-define('EVENT_STORE.CLIENT.SHARED.UUID_PB_H', true).
-record('event_store.client.shared.UUID',
        {value                  :: {structured, shared:'event_store.client.shared.UUID.Structured'()} | {string, unicode:chardata()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.SHARED.EMPTY_PB_H').
-define('EVENT_STORE.CLIENT.SHARED.EMPTY_PB_H', true).
-record('event_store.client.shared.Empty',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.SHARED.STREAMIDENTIFIER_PB_H').
-define('EVENT_STORE.CLIENT.SHARED.STREAMIDENTIFIER_PB_H', true).
-record('event_store.client.shared.StreamIdentifier',
        {streamName = <<>>      :: iodata() | undefined % = 3, optional
        }).
-endif.

-endif.
