%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(spear_proto_monitoring).
-define(spear_proto_monitoring, true).

-define(spear_proto_monitoring_gpb_version, "4.18.0").

-ifndef('EVENT_STORE.CLIENT.MONITORING.STATSREQ_PB_H').
-define('EVENT_STORE.CLIENT.MONITORING.STATSREQ_PB_H', true).
-record('event_store.client.monitoring.StatsReq',
        {use_metadata = false   :: boolean() | 0 | 1 | undefined, % = 1, optional
         refresh_time_period_in_ms = 0 :: non_neg_integer() | undefined % = 4, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.MONITORING.STATSRESP_PB_H').
-define('EVENT_STORE.CLIENT.MONITORING.STATSRESP_PB_H', true).
-record('event_store.client.monitoring.StatsResp',
        {stats = []             :: [{unicode:chardata(), unicode:chardata()}] | undefined % = 1
        }).
-endif.

-endif.
