%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(spear_proto_persistent).
-define(spear_proto_persistent, true).

-define(spear_proto_persistent_gpb_version, "4.18.0").

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.OPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadReq.Options',
        {stream_option          :: {stream_identifier, spear_proto_persistent:'event_store.client.StreamIdentifier'()} | {all, spear_proto_persistent:'event_store.client.Empty'()} | undefined, % oneof
         group_name = <<>>      :: unicode:chardata() | undefined, % = 2, optional
         buffer_size = 0        :: integer() | undefined, % = 3, optional, 32 bits
         uuid_option = undefined :: spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption'() | undefined % = 4, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.OPTIONS.UUIDOPTION_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.OPTIONS.UUIDOPTION_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption',
        {content                :: {structured, spear_proto_persistent:'event_store.client.Empty'()} | {string, spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.ACK_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.ACK_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadReq.Ack',
        {id = <<>>              :: iodata() | undefined, % = 1, optional
         ids = []               :: [spear_proto_persistent:'event_store.client.UUID'()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.NACK_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ.NACK_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadReq.Nack',
        {id = <<>>              :: iodata() | undefined, % = 1, optional
         ids = []               :: [spear_proto_persistent:'event_store.client.UUID'()] | undefined, % = 2, repeated
         action = 'Unknown'     :: 'Unknown' | 'Park' | 'Retry' | 'Skip' | 'Stop' | integer() | undefined, % = 3, optional, enum event_store.client.persistent_subscriptions.ReadReq.Nack.Action
         reason = <<>>          :: unicode:chardata() | undefined % = 4, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READREQ_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadReq',
        {content                :: {options, spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadReq.Options'()} | {ack, spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadReq.Ack'()} | {nack, spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadReq.Nack'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.READEVENT_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.READEVENT_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadResp.ReadEvent',
        {event = undefined      :: spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadResp.ReadEvent.RecordedEvent'() | undefined, % = 1, optional
         link = undefined       :: spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadResp.ReadEvent.RecordedEvent'() | undefined, % = 2, optional
         position               :: {commit_position, non_neg_integer()} | {no_position, spear_proto_persistent:'event_store.client.Empty'()} | undefined, % oneof
         count                  :: {retry_count, integer()} | {no_retry_count, spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.READEVENT.RECORDEDEVENT_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.READEVENT.RECORDEDEVENT_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadResp.ReadEvent.RecordedEvent',
        {id = undefined         :: spear_proto_persistent:'event_store.client.UUID'() | undefined, % = 1, optional
         stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined, % = 2, optional
         stream_revision = 0    :: non_neg_integer() | undefined, % = 3, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined, % = 4, optional, 64 bits
         commit_position = 0    :: non_neg_integer() | undefined, % = 5, optional, 64 bits
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 6
         custom_metadata = <<>> :: iodata() | undefined, % = 7, optional
         data = <<>>            :: iodata() | undefined % = 8, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.SUBSCRIPTIONCONFIRMATION_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP.SUBSCRIPTIONCONFIRMATION_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadResp.SubscriptionConfirmation',
        {subscription_id = <<>> :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.READRESP_PB_H', true).
-record('event_store.client.persistent_subscriptions.ReadResp',
        {content                :: {event, spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadResp.ReadEvent'()} | {subscription_confirmation, spear_proto_persistent:'event_store.client.persistent_subscriptions.ReadResp.SubscriptionConfirmation'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.OPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.Options',
        {stream_option          :: {stream, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.StreamOptions'()} | {all, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.AllOptions'()} | undefined, % oneof
         stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         group_name = <<>>      :: unicode:chardata() | undefined, % = 2, optional
         settings = undefined   :: spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.Settings'() | undefined % = 3, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.STREAMOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.STREAMOPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.StreamOptions',
        {stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         revision_option        :: {revision, non_neg_integer()} | {start, spear_proto_persistent:'event_store.client.Empty'()} | {'end', spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.AllOptions',
        {all_option             :: {position, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.Position'()} | {start, spear_proto_persistent:'event_store.client.Empty'()} | {'end', spear_proto_persistent:'event_store.client.Empty'()} | undefined, % oneof
         filter_option          :: {filter, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions'()} | {no_filter, spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS.FILTEROPTIONS.EXPRESSION_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS.FILTEROPTIONS.EXPRESSION_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions.Expression',
        {regex = <<>>           :: unicode:chardata() | undefined, % = 1, optional
         prefix = []            :: [unicode:chardata()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS.FILTEROPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.ALLOPTIONS.FILTEROPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions',
        {filter                 :: {stream_identifier, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions.Expression'()} | {event_type, spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions.Expression'()} | undefined, % oneof
         window                 :: {max, non_neg_integer()} | {count, spear_proto_persistent:'event_store.client.Empty'()} | undefined, % oneof
         checkpointIntervalMultiplier = 0 :: non_neg_integer() | undefined % = 5, optional, 32 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.POSITION_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.SETTINGS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ.SETTINGS_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq.Settings',
        {resolve_links = false  :: boolean() | 0 | 1 | undefined, % = 1, optional
         revision = 0           :: non_neg_integer() | undefined, % = 2, optional, 64 bits
         extra_statistics = false :: boolean() | 0 | 1 | undefined, % = 3, optional
         max_retry_count = 0    :: integer() | undefined, % = 5, optional, 32 bits
         min_checkpoint_count = 0 :: integer() | undefined, % = 7, optional, 32 bits
         max_checkpoint_count = 0 :: integer() | undefined, % = 8, optional, 32 bits
         max_subscriber_count = 0 :: integer() | undefined, % = 9, optional, 32 bits
         live_buffer_size = 0   :: integer() | undefined, % = 10, optional, 32 bits
         read_batch_size = 0    :: integer() | undefined, % = 11, optional, 32 bits
         history_buffer_size = 0 :: integer() | undefined, % = 12, optional, 32 bits
         named_consumer_strategy = 'DispatchToSingle' :: 'DispatchToSingle' | 'RoundRobin' | 'Pinned' | integer() | undefined, % = 13, optional, enum event_store.client.persistent_subscriptions.CreateReq.ConsumerStrategy
         message_timeout        :: {message_timeout_ticks, integer()} | {message_timeout_ms, integer()} | undefined, % oneof
         checkpoint_after       :: {checkpoint_after_ticks, integer()} | {checkpoint_after_ms, integer()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATEREQ_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateReq',
        {options = undefined    :: spear_proto_persistent:'event_store.client.persistent_subscriptions.CreateReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATERESP_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.CREATERESP_PB_H', true).
-record('event_store.client.persistent_subscriptions.CreateResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.OPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq.Options',
        {stream_option          :: {stream, spear_proto_persistent:'event_store.client.persistent_subscriptions.UpdateReq.StreamOptions'()} | {all, spear_proto_persistent:'event_store.client.persistent_subscriptions.UpdateReq.AllOptions'()} | undefined, % oneof
         stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         group_name = <<>>      :: unicode:chardata() | undefined, % = 2, optional
         settings = undefined   :: spear_proto_persistent:'event_store.client.persistent_subscriptions.UpdateReq.Settings'() | undefined % = 3, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.STREAMOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.STREAMOPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq.StreamOptions',
        {stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         revision_option        :: {revision, non_neg_integer()} | {start, spear_proto_persistent:'event_store.client.Empty'()} | {'end', spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.ALLOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.ALLOPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq.AllOptions',
        {all_option             :: {position, spear_proto_persistent:'event_store.client.persistent_subscriptions.UpdateReq.Position'()} | {start, spear_proto_persistent:'event_store.client.Empty'()} | {'end', spear_proto_persistent:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.POSITION_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.SETTINGS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ.SETTINGS_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq.Settings',
        {resolve_links = false  :: boolean() | 0 | 1 | undefined, % = 1, optional
         revision = 0           :: non_neg_integer() | undefined, % = 2, optional, 64 bits
         extra_statistics = false :: boolean() | 0 | 1 | undefined, % = 3, optional
         max_retry_count = 0    :: integer() | undefined, % = 5, optional, 32 bits
         min_checkpoint_count = 0 :: integer() | undefined, % = 7, optional, 32 bits
         max_checkpoint_count = 0 :: integer() | undefined, % = 8, optional, 32 bits
         max_subscriber_count = 0 :: integer() | undefined, % = 9, optional, 32 bits
         live_buffer_size = 0   :: integer() | undefined, % = 10, optional, 32 bits
         read_batch_size = 0    :: integer() | undefined, % = 11, optional, 32 bits
         history_buffer_size = 0 :: integer() | undefined, % = 12, optional, 32 bits
         named_consumer_strategy = 'DispatchToSingle' :: 'DispatchToSingle' | 'RoundRobin' | 'Pinned' | integer() | undefined, % = 13, optional, enum event_store.client.persistent_subscriptions.UpdateReq.ConsumerStrategy
         message_timeout        :: {message_timeout_ticks, integer()} | {message_timeout_ms, integer()} | undefined, % oneof
         checkpoint_after       :: {checkpoint_after_ticks, integer()} | {checkpoint_after_ms, integer()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATEREQ_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateReq',
        {options = undefined    :: spear_proto_persistent:'event_store.client.persistent_subscriptions.UpdateReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATERESP_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.UPDATERESP_PB_H', true).
-record('event_store.client.persistent_subscriptions.UpdateResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETEREQ.OPTIONS_PB_H', true).
-record('event_store.client.persistent_subscriptions.DeleteReq.Options',
        {stream_option          :: {stream_identifier, spear_proto_persistent:'event_store.client.StreamIdentifier'()} | {all, spear_proto_persistent:'event_store.client.Empty'()} | undefined, % oneof
         group_name = <<>>      :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETEREQ_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETEREQ_PB_H', true).
-record('event_store.client.persistent_subscriptions.DeleteReq',
        {options = undefined    :: spear_proto_persistent:'event_store.client.persistent_subscriptions.DeleteReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETERESP_PB_H').
-define('EVENT_STORE.CLIENT.PERSISTENT_SUBSCRIPTIONS.DELETERESP_PB_H', true).
-record('event_store.client.persistent_subscriptions.DeleteResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UUID.STRUCTURED_PB_H').
-define('EVENT_STORE.CLIENT.UUID.STRUCTURED_PB_H', true).
-record('event_store.client.UUID.Structured',
        {most_significant_bits = 0 :: integer() | undefined, % = 1, optional, 64 bits
         least_significant_bits = 0 :: integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UUID_PB_H').
-define('EVENT_STORE.CLIENT.UUID_PB_H', true).
-record('event_store.client.UUID',
        {value                  :: {structured, spear_proto_persistent:'event_store.client.UUID.Structured'()} | {string, unicode:chardata()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.EMPTY_PB_H').
-define('EVENT_STORE.CLIENT.EMPTY_PB_H', true).
-record('event_store.client.Empty',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMIDENTIFIER_PB_H').
-define('EVENT_STORE.CLIENT.STREAMIDENTIFIER_PB_H', true).
-record('event_store.client.StreamIdentifier',
        {stream_name = <<>>     :: iodata() | undefined % = 3, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.ALLSTREAMPOSITION_PB_H').
-define('EVENT_STORE.CLIENT.ALLSTREAMPOSITION_PB_H', true).
-record('event_store.client.AllStreamPosition',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.WRONGEXPECTEDVERSION_PB_H').
-define('EVENT_STORE.CLIENT.WRONGEXPECTEDVERSION_PB_H', true).
-record('event_store.client.WrongExpectedVersion',
        {current_stream_revision_option :: {current_stream_revision, non_neg_integer()} | {current_no_stream, spear_proto_persistent:'google.protobuf.Empty'()} | undefined, % oneof
         expected_stream_position_option :: {expected_stream_position, non_neg_integer()} | {expected_any, spear_proto_persistent:'google.protobuf.Empty'()} | {expected_stream_exists, spear_proto_persistent:'google.protobuf.Empty'()} | {expected_no_stream, spear_proto_persistent:'google.protobuf.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.ACCESSDENIED_PB_H').
-define('EVENT_STORE.CLIENT.ACCESSDENIED_PB_H', true).
-record('event_store.client.AccessDenied',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMDELETED_PB_H').
-define('EVENT_STORE.CLIENT.STREAMDELETED_PB_H', true).
-record('event_store.client.StreamDeleted',
        {stream_identifier = undefined :: spear_proto_persistent:'event_store.client.StreamIdentifier'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.TIMEOUT_PB_H').
-define('EVENT_STORE.CLIENT.TIMEOUT_PB_H', true).
-record('event_store.client.Timeout',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UNKNOWN_PB_H').
-define('EVENT_STORE.CLIENT.UNKNOWN_PB_H', true).
-record('event_store.client.Unknown',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.INVALIDTRANSACTION_PB_H').
-define('EVENT_STORE.CLIENT.INVALIDTRANSACTION_PB_H', true).
-record('event_store.client.InvalidTransaction',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.MAXIMUMAPPENDSIZEEXCEEDED_PB_H').
-define('EVENT_STORE.CLIENT.MAXIMUMAPPENDSIZEEXCEEDED_PB_H', true).
-record('event_store.client.MaximumAppendSizeExceeded',
        {maxAppendSize = 0      :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.BADREQUEST_PB_H').
-define('EVENT_STORE.CLIENT.BADREQUEST_PB_H', true).
-record('event_store.client.BadRequest',
        {message = <<>>         :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.EMPTY_PB_H').
-define('GOOGLE.PROTOBUF.EMPTY_PB_H', true).
-record('google.protobuf.Empty',
        {
        }).
-endif.

-endif.
