%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(spear_proto_streams).
-define(spear_proto_streams, true).

-define(spear_proto_streams_gpb_version, "4.18.0").

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS_PB_H', true).
-record('event_store.client.streams.ReadReq.Options',
        {stream_option          :: {stream, spear_proto_streams:'event_store.client.streams.ReadReq.Options.StreamOptions'()} | {all, spear_proto_streams:'event_store.client.streams.ReadReq.Options.AllOptions'()} | undefined, % oneof
         read_direction = 'Forwards' :: 'Forwards' | 'Backwards' | integer() | undefined, % = 3, optional, enum event_store.client.streams.ReadReq.Options.ReadDirection
         resolve_links = false  :: boolean() | 0 | 1 | undefined, % = 4, optional
         count_option           :: {count, non_neg_integer()} | {subscription, spear_proto_streams:'event_store.client.streams.ReadReq.Options.SubscriptionOptions'()} | undefined, % oneof
         filter_option          :: {filter, spear_proto_streams:'event_store.client.streams.ReadReq.Options.FilterOptions'()} | {no_filter, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         uuid_option = undefined :: spear_proto_streams:'event_store.client.streams.ReadReq.Options.UUIDOption'() | undefined % = 9, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.UUIDOPTION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.UUIDOPTION_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.UUIDOption',
        {content                :: {structured, spear_proto_streams:'event_store.client.Empty'()} | {string, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.FILTEROPTIONS.EXPRESSION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.FILTEROPTIONS.EXPRESSION_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.FilterOptions.Expression',
        {regex = <<>>           :: unicode:chardata() | undefined, % = 1, optional
         prefix = []            :: [unicode:chardata()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.FILTEROPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.FILTEROPTIONS_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.FilterOptions',
        {filter                 :: {stream_identifier, spear_proto_streams:'event_store.client.streams.ReadReq.Options.FilterOptions.Expression'()} | {event_type, spear_proto_streams:'event_store.client.streams.ReadReq.Options.FilterOptions.Expression'()} | undefined, % oneof
         window                 :: {max, non_neg_integer()} | {count, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         checkpointIntervalMultiplier = 0 :: non_neg_integer() | undefined % = 5, optional, 32 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.POSITION_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.SUBSCRIPTIONOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.SUBSCRIPTIONOPTIONS_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.SubscriptionOptions',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.ALLOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.ALLOPTIONS_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.AllOptions',
        {all_option             :: {position, spear_proto_streams:'event_store.client.streams.ReadReq.Options.Position'()} | {start, spear_proto_streams:'event_store.client.Empty'()} | {'end', spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.STREAMOPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ.OPTIONS.STREAMOPTIONS_PB_H', true).
-record('event_store.client.streams.ReadReq.Options.StreamOptions',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         revision_option        :: {revision, non_neg_integer()} | {start, spear_proto_streams:'event_store.client.Empty'()} | {'end', spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READREQ_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READREQ_PB_H', true).
-record('event_store.client.streams.ReadReq',
        {options = undefined    :: spear_proto_streams:'event_store.client.streams.ReadReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP.READEVENT_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP.READEVENT_PB_H', true).
-record('event_store.client.streams.ReadResp.ReadEvent',
        {event = undefined      :: spear_proto_streams:'event_store.client.streams.ReadResp.ReadEvent.RecordedEvent'() | undefined, % = 1, optional
         link = undefined       :: spear_proto_streams:'event_store.client.streams.ReadResp.ReadEvent.RecordedEvent'() | undefined, % = 2, optional
         position               :: {commit_position, non_neg_integer()} | {no_position, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP.READEVENT.RECORDEDEVENT_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP.READEVENT.RECORDEDEVENT_PB_H', true).
-record('event_store.client.streams.ReadResp.ReadEvent.RecordedEvent',
        {id = undefined         :: spear_proto_streams:'event_store.client.UUID'() | undefined, % = 1, optional
         stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 2, optional
         stream_revision = 0    :: non_neg_integer() | undefined, % = 3, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined, % = 4, optional, 64 bits
         commit_position = 0    :: non_neg_integer() | undefined, % = 5, optional, 64 bits
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 6
         custom_metadata = <<>> :: iodata() | undefined, % = 7, optional
         data = <<>>            :: iodata() | undefined % = 8, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP.SUBSCRIPTIONCONFIRMATION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP.SUBSCRIPTIONCONFIRMATION_PB_H', true).
-record('event_store.client.streams.ReadResp.SubscriptionConfirmation',
        {subscription_id = <<>> :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP.CHECKPOINT_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP.CHECKPOINT_PB_H', true).
-record('event_store.client.streams.ReadResp.Checkpoint',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP.STREAMNOTFOUND_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP.STREAMNOTFOUND_PB_H', true).
-record('event_store.client.streams.ReadResp.StreamNotFound',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.READRESP_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.READRESP_PB_H', true).
-record('event_store.client.streams.ReadResp',
        {content                :: {event, spear_proto_streams:'event_store.client.streams.ReadResp.ReadEvent'()} | {confirmation, spear_proto_streams:'event_store.client.streams.ReadResp.SubscriptionConfirmation'()} | {checkpoint, spear_proto_streams:'event_store.client.streams.ReadResp.Checkpoint'()} | {stream_not_found, spear_proto_streams:'event_store.client.streams.ReadResp.StreamNotFound'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDREQ.OPTIONS_PB_H', true).
-record('event_store.client.streams.AppendReq.Options',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         expected_stream_revision :: {revision, non_neg_integer()} | {no_stream, spear_proto_streams:'event_store.client.Empty'()} | {any, spear_proto_streams:'event_store.client.Empty'()} | {stream_exists, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDREQ.PROPOSEDMESSAGE_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDREQ.PROPOSEDMESSAGE_PB_H', true).
-record('event_store.client.streams.AppendReq.ProposedMessage',
        {id = undefined         :: spear_proto_streams:'event_store.client.UUID'() | undefined, % = 1, optional
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 2
         custom_metadata = <<>> :: iodata() | undefined, % = 3, optional
         data = <<>>            :: iodata() | undefined % = 4, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDREQ_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDREQ_PB_H', true).
-record('event_store.client.streams.AppendReq',
        {content                :: {options, spear_proto_streams:'event_store.client.streams.AppendReq.Options'()} | {proposed_message, spear_proto_streams:'event_store.client.streams.AppendReq.ProposedMessage'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.POSITION_PB_H', true).
-record('event_store.client.streams.AppendResp.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.SUCCESS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.SUCCESS_PB_H', true).
-record('event_store.client.streams.AppendResp.Success',
        {current_revision_option :: {current_revision, non_neg_integer()} | {no_stream, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         position_option        :: {position, spear_proto_streams:'event_store.client.streams.AppendResp.Position'()} | {no_position, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.WRONGEXPECTEDVERSION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDRESP.WRONGEXPECTEDVERSION_PB_H', true).
-record('event_store.client.streams.AppendResp.WrongExpectedVersion',
        {current_revision_option_20_6_0 :: {current_revision_20_6_0, non_neg_integer()} | {no_stream_20_6_0, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         expected_revision_option_20_6_0 :: {expected_revision_20_6_0, non_neg_integer()} | {any_20_6_0, spear_proto_streams:'event_store.client.Empty'()} | {stream_exists_20_6_0, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         current_revision_option :: {current_revision, non_neg_integer()} | {current_no_stream, spear_proto_streams:'event_store.client.Empty'()} | undefined, % oneof
         expected_revision_option :: {expected_revision, non_neg_integer()} | {expected_any, spear_proto_streams:'event_store.client.Empty'()} | {expected_stream_exists, spear_proto_streams:'event_store.client.Empty'()} | {expected_no_stream, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.APPENDRESP_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.APPENDRESP_PB_H', true).
-record('event_store.client.streams.AppendResp',
        {result                 :: {success, spear_proto_streams:'event_store.client.streams.AppendResp.Success'()} | {wrong_expected_version, spear_proto_streams:'event_store.client.streams.AppendResp.WrongExpectedVersion'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ.OPTIONS_PB_H', true).
-record('event_store.client.streams.BatchAppendReq.Options',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         expected_stream_position :: {stream_position, non_neg_integer()} | {no_stream, spear_proto_streams:'google.protobuf.Empty'()} | {any, spear_proto_streams:'google.protobuf.Empty'()} | {stream_exists, spear_proto_streams:'google.protobuf.Empty'()} | undefined, % oneof
         deadline = undefined   :: spear_proto_streams:'google.protobuf.Timestamp'() | undefined % = 6, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ.PROPOSEDMESSAGE_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ.PROPOSEDMESSAGE_PB_H', true).
-record('event_store.client.streams.BatchAppendReq.ProposedMessage',
        {id = undefined         :: spear_proto_streams:'event_store.client.UUID'() | undefined, % = 1, optional
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 2
         custom_metadata = <<>> :: iodata() | undefined, % = 3, optional
         data = <<>>            :: iodata() | undefined % = 4, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDREQ_PB_H', true).
-record('event_store.client.streams.BatchAppendReq',
        {correlation_id = undefined :: spear_proto_streams:'event_store.client.UUID'() | undefined, % = 1, optional
         options = undefined    :: spear_proto_streams:'event_store.client.streams.BatchAppendReq.Options'() | undefined, % = 2, optional
         proposed_messages = [] :: [spear_proto_streams:'event_store.client.streams.BatchAppendReq.ProposedMessage'()] | undefined, % = 3, repeated
         is_final = false       :: boolean() | 0 | 1 | undefined % = 4, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDRESP.SUCCESS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDRESP.SUCCESS_PB_H', true).
-record('event_store.client.streams.BatchAppendResp.Success',
        {current_revision_option :: {current_revision, non_neg_integer()} | {no_stream, spear_proto_streams:'google.protobuf.Empty'()} | undefined, % oneof
         position_option        :: {position, spear_proto_streams:'event_store.client.AllStreamPosition'()} | {no_position, spear_proto_streams:'google.protobuf.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDRESP_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.BATCHAPPENDRESP_PB_H', true).
-record('event_store.client.streams.BatchAppendResp',
        {correlation_id = undefined :: spear_proto_streams:'event_store.client.UUID'() | undefined, % = 1, optional
         result                 :: {error, spear_proto_streams:'google.rpc.Status'()} | {success, spear_proto_streams:'event_store.client.streams.BatchAppendResp.Success'()} | undefined, % oneof
         stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 4, optional
         expected_stream_position :: {stream_position, non_neg_integer()} | {no_stream, spear_proto_streams:'google.protobuf.Empty'()} | {any, spear_proto_streams:'google.protobuf.Empty'()} | {stream_exists, spear_proto_streams:'google.protobuf.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.DELETEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.DELETEREQ.OPTIONS_PB_H', true).
-record('event_store.client.streams.DeleteReq.Options',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         expected_stream_revision :: {revision, non_neg_integer()} | {no_stream, spear_proto_streams:'event_store.client.Empty'()} | {any, spear_proto_streams:'event_store.client.Empty'()} | {stream_exists, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.DELETEREQ_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.DELETEREQ_PB_H', true).
-record('event_store.client.streams.DeleteReq',
        {options = undefined    :: spear_proto_streams:'event_store.client.streams.DeleteReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.DELETERESP.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.DELETERESP.POSITION_PB_H', true).
-record('event_store.client.streams.DeleteResp.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.DELETERESP_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.DELETERESP_PB_H', true).
-record('event_store.client.streams.DeleteResp',
        {position_option        :: {position, spear_proto_streams:'event_store.client.streams.DeleteResp.Position'()} | {no_position, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.TOMBSTONEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.TOMBSTONEREQ.OPTIONS_PB_H', true).
-record('event_store.client.streams.TombstoneReq.Options',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined, % = 1, optional
         expected_stream_revision :: {revision, non_neg_integer()} | {no_stream, spear_proto_streams:'event_store.client.Empty'()} | {any, spear_proto_streams:'event_store.client.Empty'()} | {stream_exists, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.TOMBSTONEREQ_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.TOMBSTONEREQ_PB_H', true).
-record('event_store.client.streams.TombstoneReq',
        {options = undefined    :: spear_proto_streams:'event_store.client.streams.TombstoneReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.TOMBSTONERESP.POSITION_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.TOMBSTONERESP.POSITION_PB_H', true).
-record('event_store.client.streams.TombstoneResp.Position',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMS.TOMBSTONERESP_PB_H').
-define('EVENT_STORE.CLIENT.STREAMS.TOMBSTONERESP_PB_H', true).
-record('event_store.client.streams.TombstoneResp',
        {position_option        :: {position, spear_proto_streams:'event_store.client.streams.TombstoneResp.Position'()} | {no_position, spear_proto_streams:'event_store.client.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UUID.STRUCTURED_PB_H').
-define('EVENT_STORE.CLIENT.UUID.STRUCTURED_PB_H', true).
-record('event_store.client.UUID.Structured',
        {most_significant_bits = 0 :: integer() | undefined, % = 1, optional, 64 bits
         least_significant_bits = 0 :: integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UUID_PB_H').
-define('EVENT_STORE.CLIENT.UUID_PB_H', true).
-record('event_store.client.UUID',
        {value                  :: {structured, spear_proto_streams:'event_store.client.UUID.Structured'()} | {string, unicode:chardata()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.EMPTY_PB_H').
-define('EVENT_STORE.CLIENT.EMPTY_PB_H', true).
-record('event_store.client.Empty',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMIDENTIFIER_PB_H').
-define('EVENT_STORE.CLIENT.STREAMIDENTIFIER_PB_H', true).
-record('event_store.client.StreamIdentifier',
        {stream_name = <<>>     :: iodata() | undefined % = 3, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.ALLSTREAMPOSITION_PB_H').
-define('EVENT_STORE.CLIENT.ALLSTREAMPOSITION_PB_H', true).
-record('event_store.client.AllStreamPosition',
        {commit_position = 0    :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         prepare_position = 0   :: non_neg_integer() | undefined % = 2, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.WRONGEXPECTEDVERSION_PB_H').
-define('EVENT_STORE.CLIENT.WRONGEXPECTEDVERSION_PB_H', true).
-record('event_store.client.WrongExpectedVersion',
        {current_stream_revision_option :: {current_stream_revision, non_neg_integer()} | {current_no_stream, spear_proto_streams:'google.protobuf.Empty'()} | undefined, % oneof
         expected_stream_position_option :: {expected_stream_position, non_neg_integer()} | {expected_any, spear_proto_streams:'google.protobuf.Empty'()} | {expected_stream_exists, spear_proto_streams:'google.protobuf.Empty'()} | {expected_no_stream, spear_proto_streams:'google.protobuf.Empty'()} | undefined % oneof
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.ACCESSDENIED_PB_H').
-define('EVENT_STORE.CLIENT.ACCESSDENIED_PB_H', true).
-record('event_store.client.AccessDenied',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.STREAMDELETED_PB_H').
-define('EVENT_STORE.CLIENT.STREAMDELETED_PB_H', true).
-record('event_store.client.StreamDeleted',
        {stream_identifier = undefined :: spear_proto_streams:'event_store.client.StreamIdentifier'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.TIMEOUT_PB_H').
-define('EVENT_STORE.CLIENT.TIMEOUT_PB_H', true).
-record('event_store.client.Timeout',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.UNKNOWN_PB_H').
-define('EVENT_STORE.CLIENT.UNKNOWN_PB_H', true).
-record('event_store.client.Unknown',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.INVALIDTRANSACTION_PB_H').
-define('EVENT_STORE.CLIENT.INVALIDTRANSACTION_PB_H', true).
-record('event_store.client.InvalidTransaction',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.MAXIMUMAPPENDSIZEEXCEEDED_PB_H').
-define('EVENT_STORE.CLIENT.MAXIMUMAPPENDSIZEEXCEEDED_PB_H', true).
-record('event_store.client.MaximumAppendSizeExceeded',
        {maxAppendSize = 0      :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.BADREQUEST_PB_H').
-define('EVENT_STORE.CLIENT.BADREQUEST_PB_H', true).
-record('event_store.client.BadRequest',
        {message = <<>>         :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('GOOGLE.RPC.STATUS_PB_H').
-define('GOOGLE.RPC.STATUS_PB_H', true).
-record('google.rpc.Status',
        {code = 'OK'            :: 'OK' | 'CANCELLED' | 'UNKNOWN' | 'INVALID_ARGUMENT' | 'DEADLINE_EXCEEDED' | 'NOT_FOUND' | 'ALREADY_EXISTS' | 'PERMISSION_DENIED' | 'UNAUTHENTICATED' | 'RESOURCE_EXHAUSTED' | 'FAILED_PRECONDITION' | 'ABORTED' | 'OUT_OF_RANGE' | 'UNIMPLEMENTED' | 'INTERNAL' | 'UNAVAILABLE' | 'DATA_LOSS' | integer() | undefined, % = 1, optional, enum google.rpc.Code
         message = <<>>         :: unicode:chardata() | undefined, % = 2, optional
         details = undefined    :: spear_proto_streams:'google.protobuf.Any'() | undefined % = 3, optional
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.EMPTY_PB_H').
-define('GOOGLE.PROTOBUF.EMPTY_PB_H', true).
-record('google.protobuf.Empty',
        {
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.TIMESTAMP_PB_H').
-define('GOOGLE.PROTOBUF.TIMESTAMP_PB_H', true).
-record('google.protobuf.Timestamp',
        {seconds = 0            :: integer() | undefined, % = 1, optional, 64 bits
         nanos = 0              :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ANY_PB_H').
-define('GOOGLE.PROTOBUF.ANY_PB_H', true).
-record('google.protobuf.Any',
        {type_url = <<>>        :: unicode:chardata() | undefined, % = 1, optional
         value = <<>>           :: iodata() | undefined % = 2, optional
        }).
-endif.

-endif.
