%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(spear_proto_status).
-define(spear_proto_status, true).

-define(spear_proto_status_gpb_version, "4.18.0").

-ifndef('GOOGLE.RPC.STATUS_PB_H').
-define('GOOGLE.RPC.STATUS_PB_H', true).
-record('google.rpc.Status',
        {code = 'OK'            :: 'OK' | 'CANCELLED' | 'UNKNOWN' | 'INVALID_ARGUMENT' | 'DEADLINE_EXCEEDED' | 'NOT_FOUND' | 'ALREADY_EXISTS' | 'PERMISSION_DENIED' | 'UNAUTHENTICATED' | 'RESOURCE_EXHAUSTED' | 'FAILED_PRECONDITION' | 'ABORTED' | 'OUT_OF_RANGE' | 'UNIMPLEMENTED' | 'INTERNAL' | 'UNAVAILABLE' | 'DATA_LOSS' | integer() | undefined, % = 1, optional, enum google.rpc.Code
         message = <<>>         :: unicode:chardata() | undefined, % = 2, optional
         details = undefined    :: spear_proto_status:'google.protobuf.Any'() | undefined % = 3, optional
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.ANY_PB_H').
-define('GOOGLE.PROTOBUF.ANY_PB_H', true).
-record('google.protobuf.Any',
        {type_url = <<>>        :: unicode:chardata() | undefined, % = 1, optional
         value = <<>>           :: iodata() | undefined % = 2, optional
        }).
-endif.

-endif.
