%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0
%% Version source: file
-module(spear_proto_status).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_google.rpc.Code'/1, 'enum_value_by_symbol_google.rpc.Code'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("spear_proto_status.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'google.rpc.Code'() :: 'OK' | 'CANCELLED' | 'UNKNOWN' | 'INVALID_ARGUMENT' | 'DEADLINE_EXCEEDED' | 'NOT_FOUND' | 'ALREADY_EXISTS' | 'PERMISSION_DENIED' | 'UNAUTHENTICATED' | 'RESOURCE_EXHAUSTED' | 'FAILED_PRECONDITION' | 'ABORTED' | 'OUT_OF_RANGE' | 'UNIMPLEMENTED' | 'INTERNAL' | 'UNAVAILABLE' | 'DATA_LOSS'.
-export_type(['google.rpc.Code'/0]).

%% message types
-type 'google.rpc.Status'() :: #'google.rpc.Status'{}.

-type 'google.protobuf.Any'() :: #'google.protobuf.Any'{}.

-export_type(['google.rpc.Status'/0, 'google.protobuf.Any'/0]).
-type '$msg_name'() :: 'google.rpc.Status' | 'google.protobuf.Any'.
-type '$msg'() :: 'google.rpc.Status'() | 'google.protobuf.Any'().
-export_type(['$msg_name'/0, '$msg'/0]).

-dialyzer({no_underspecs, encode_msg/1}).
-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-dialyzer({no_underspecs, encode_msg/2}).
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-dialyzer({no_underspecs, encode_msg/3}).
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'google.rpc.Status' -> 'encode_msg_google.rpc.Status'(id(Msg, TrUserData), TrUserData);
        'google.protobuf.Any' -> 'encode_msg_google.protobuf.Any'(id(Msg, TrUserData), TrUserData)
    end.


'encode_msg_google.rpc.Status'(Msg, TrUserData) -> 'encode_msg_google.rpc.Status'(Msg, <<>>, TrUserData).


'encode_msg_google.rpc.Status'(#'google.rpc.Status'{code = F1, message = F2, details = F3}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    if TrF1 =:= 'OK'; TrF1 =:= 0 -> Bin;
                       true -> 'e_enum_google.rpc.Code'(TrF1, <<Bin/binary, 8>>, TrUserData)
                    end
                end
         end,
    B2 = if F2 == undefined -> B1;
            true ->
                begin
                    TrF2 = id(F2, TrUserData),
                    case is_empty_string(TrF2) of
                        true -> B1;
                        false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                    end
                end
         end,
    if F3 == undefined -> B2;
       true ->
           begin
               TrF3 = id(F3, TrUserData),
               if TrF3 =:= undefined -> B2;
                  true -> 'e_mfield_google.rpc.Status_details'(TrF3, <<B2/binary, 26>>, TrUserData)
               end
           end
    end.

'encode_msg_google.protobuf.Any'(Msg, TrUserData) -> 'encode_msg_google.protobuf.Any'(Msg, <<>>, TrUserData).


'encode_msg_google.protobuf.Any'(#'google.protobuf.Any'{type_url = F1, value = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true ->
                begin
                    TrF1 = id(F1, TrUserData),
                    case is_empty_string(TrF1) of
                        true -> Bin;
                        false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                    end
                end
         end,
    if F2 == undefined -> B1;
       true ->
           begin
               TrF2 = id(F2, TrUserData),
               case iolist_size(TrF2) of
                   0 -> B1;
                   _ -> e_type_bytes(TrF2, <<B1/binary, 18>>, TrUserData)
               end
           end
    end.

'e_mfield_google.rpc.Status_details'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_google.protobuf.Any'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_enum_google.rpc.Code'('OK', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_google.rpc.Code'('CANCELLED', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_google.rpc.Code'('UNKNOWN', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_google.rpc.Code'('INVALID_ARGUMENT', Bin, _TrUserData) -> <<Bin/binary, 3>>;
'e_enum_google.rpc.Code'('DEADLINE_EXCEEDED', Bin, _TrUserData) -> <<Bin/binary, 4>>;
'e_enum_google.rpc.Code'('NOT_FOUND', Bin, _TrUserData) -> <<Bin/binary, 5>>;
'e_enum_google.rpc.Code'('ALREADY_EXISTS', Bin, _TrUserData) -> <<Bin/binary, 6>>;
'e_enum_google.rpc.Code'('PERMISSION_DENIED', Bin, _TrUserData) -> <<Bin/binary, 7>>;
'e_enum_google.rpc.Code'('UNAUTHENTICATED', Bin, _TrUserData) -> <<Bin/binary, 16>>;
'e_enum_google.rpc.Code'('RESOURCE_EXHAUSTED', Bin, _TrUserData) -> <<Bin/binary, 8>>;
'e_enum_google.rpc.Code'('FAILED_PRECONDITION', Bin, _TrUserData) -> <<Bin/binary, 9>>;
'e_enum_google.rpc.Code'('ABORTED', Bin, _TrUserData) -> <<Bin/binary, 10>>;
'e_enum_google.rpc.Code'('OUT_OF_RANGE', Bin, _TrUserData) -> <<Bin/binary, 11>>;
'e_enum_google.rpc.Code'('UNIMPLEMENTED', Bin, _TrUserData) -> <<Bin/binary, 12>>;
'e_enum_google.rpc.Code'('INTERNAL', Bin, _TrUserData) -> <<Bin/binary, 13>>;
'e_enum_google.rpc.Code'('UNAVAILABLE', Bin, _TrUserData) -> <<Bin/binary, 14>>;
'e_enum_google.rpc.Code'('DATA_LOSS', Bin, _TrUserData) -> <<Bin/binary, 15>>;
'e_enum_google.rpc.Code'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('google.rpc.Status', Bin, TrUserData) -> id('decode_msg_google.rpc.Status'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('google.protobuf.Any', Bin, TrUserData) -> id('decode_msg_google.protobuf.Any'(Bin, TrUserData), TrUserData).



'decode_msg_google.rpc.Status'(Bin, TrUserData) -> 'dfp_read_field_def_google.rpc.Status'(Bin, 0, 0, 0, id('OK', TrUserData), id(<<>>, TrUserData), id(undefined, TrUserData), TrUserData).

'dfp_read_field_def_google.rpc.Status'(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'd_field_google.rpc.Status_code'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
'dfp_read_field_def_google.rpc.Status'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'd_field_google.rpc.Status_message'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
'dfp_read_field_def_google.rpc.Status'(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'd_field_google.rpc.Status_details'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
'dfp_read_field_def_google.rpc.Status'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #'google.rpc.Status'{code = F@_1, message = F@_2, details = F@_3};
'dfp_read_field_def_google.rpc.Status'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'dg_read_field_def_google.rpc.Status'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

'dg_read_field_def_google.rpc.Status'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_google.rpc.Status'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
'dg_read_field_def_google.rpc.Status'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> 'd_field_google.rpc.Status_code'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        18 -> 'd_field_google.rpc.Status_message'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        26 -> 'd_field_google.rpc.Status_details'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_google.rpc.Status'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> 'skip_64_google.rpc.Status'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> 'skip_length_delimited_google.rpc.Status'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> 'skip_group_google.rpc.Status'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> 'skip_32_google.rpc.Status'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
'dg_read_field_def_google.rpc.Status'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #'google.rpc.Status'{code = F@_1, message = F@_2, details = F@_3}.

'd_field_google.rpc.Status_code'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> 'd_field_google.rpc.Status_code'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
'd_field_google.rpc.Status_code'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_google.rpc.Code'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    'dfp_read_field_def_google.rpc.Status'(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

'd_field_google.rpc.Status_message'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> 'd_field_google.rpc.Status_message'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
'd_field_google.rpc.Status_message'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_google.rpc.Status'(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

'd_field_google.rpc.Status_details'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> 'd_field_google.rpc.Status_details'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
'd_field_google.rpc.Status_details'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_google.protobuf.Any'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_google.rpc.Status'(RestF,
                                           0,
                                           0,
                                           F,
                                           F@_1,
                                           F@_2,
                                           if Prev == undefined -> NewFValue;
                                              true -> 'merge_msg_google.protobuf.Any'(Prev, NewFValue, TrUserData)
                                           end,
                                           TrUserData).

'skip_varint_google.rpc.Status'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'skip_varint_google.rpc.Status'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
'skip_varint_google.rpc.Status'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'dfp_read_field_def_google.rpc.Status'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

'skip_length_delimited_google.rpc.Status'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> 'skip_length_delimited_google.rpc.Status'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
'skip_length_delimited_google.rpc.Status'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_google.rpc.Status'(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

'skip_group_google.rpc.Status'(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_google.rpc.Status'(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

'skip_32_google.rpc.Status'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'dfp_read_field_def_google.rpc.Status'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

'skip_64_google.rpc.Status'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> 'dfp_read_field_def_google.rpc.Status'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

'decode_msg_google.protobuf.Any'(Bin, TrUserData) -> 'dfp_read_field_def_google.protobuf.Any'(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

'dfp_read_field_def_google.protobuf.Any'(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_google.protobuf.Any_type_url'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_google.protobuf.Any'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_google.protobuf.Any_value'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_google.protobuf.Any'(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'google.protobuf.Any'{type_url = F@_1, value = F@_2};
'dfp_read_field_def_google.protobuf.Any'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dg_read_field_def_google.protobuf.Any'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

'dg_read_field_def_google.protobuf.Any'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_google.protobuf.Any'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'dg_read_field_def_google.protobuf.Any'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> 'd_field_google.protobuf.Any_type_url'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> 'd_field_google.protobuf.Any_value'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_google.protobuf.Any'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> 'skip_64_google.protobuf.Any'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> 'skip_length_delimited_google.protobuf.Any'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> 'skip_group_google.protobuf.Any'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> 'skip_32_google.protobuf.Any'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
'dg_read_field_def_google.protobuf.Any'(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'google.protobuf.Any'{type_url = F@_1, value = F@_2}.

'd_field_google.protobuf.Any_type_url'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_google.protobuf.Any_type_url'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_google.protobuf.Any_type_url'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_google.protobuf.Any'(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

'd_field_google.protobuf.Any_value'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_google.protobuf.Any_value'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_google.protobuf.Any_value'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_google.protobuf.Any'(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

'skip_varint_google.protobuf.Any'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'skip_varint_google.protobuf.Any'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'skip_varint_google.protobuf.Any'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_google.protobuf.Any'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_length_delimited_google.protobuf.Any'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'skip_length_delimited_google.protobuf.Any'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'skip_length_delimited_google.protobuf.Any'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_google.protobuf.Any'(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

'skip_group_google.protobuf.Any'(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_google.protobuf.Any'(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

'skip_32_google.protobuf.Any'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_google.protobuf.Any'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_64_google.protobuf.Any'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_google.protobuf.Any'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'd_enum_google.rpc.Code'(0) -> 'OK';
'd_enum_google.rpc.Code'(1) -> 'CANCELLED';
'd_enum_google.rpc.Code'(2) -> 'UNKNOWN';
'd_enum_google.rpc.Code'(3) -> 'INVALID_ARGUMENT';
'd_enum_google.rpc.Code'(4) -> 'DEADLINE_EXCEEDED';
'd_enum_google.rpc.Code'(5) -> 'NOT_FOUND';
'd_enum_google.rpc.Code'(6) -> 'ALREADY_EXISTS';
'd_enum_google.rpc.Code'(7) -> 'PERMISSION_DENIED';
'd_enum_google.rpc.Code'(16) -> 'UNAUTHENTICATED';
'd_enum_google.rpc.Code'(8) -> 'RESOURCE_EXHAUSTED';
'd_enum_google.rpc.Code'(9) -> 'FAILED_PRECONDITION';
'd_enum_google.rpc.Code'(10) -> 'ABORTED';
'd_enum_google.rpc.Code'(11) -> 'OUT_OF_RANGE';
'd_enum_google.rpc.Code'(12) -> 'UNIMPLEMENTED';
'd_enum_google.rpc.Code'(13) -> 'INTERNAL';
'd_enum_google.rpc.Code'(14) -> 'UNAVAILABLE';
'd_enum_google.rpc.Code'(15) -> 'DATA_LOSS';
'd_enum_google.rpc.Code'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'google.rpc.Status' -> 'merge_msg_google.rpc.Status'(Prev, New, TrUserData);
        'google.protobuf.Any' -> 'merge_msg_google.protobuf.Any'(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,'merge_msg_google.rpc.Status'/3}).
'merge_msg_google.rpc.Status'(#'google.rpc.Status'{code = PFcode, message = PFmessage, details = PFdetails}, #'google.rpc.Status'{code = NFcode, message = NFmessage, details = NFdetails}, TrUserData) ->
    #'google.rpc.Status'{code =
                             if NFcode =:= undefined -> PFcode;
                                true -> NFcode
                             end,
                         message =
                             if NFmessage =:= undefined -> PFmessage;
                                true -> NFmessage
                             end,
                         details =
                             if PFdetails /= undefined, NFdetails /= undefined -> 'merge_msg_google.protobuf.Any'(PFdetails, NFdetails, TrUserData);
                                PFdetails == undefined -> NFdetails;
                                NFdetails == undefined -> PFdetails
                             end}.

-compile({nowarn_unused_function,'merge_msg_google.protobuf.Any'/3}).
'merge_msg_google.protobuf.Any'(#'google.protobuf.Any'{type_url = PFtype_url, value = PFvalue}, #'google.protobuf.Any'{type_url = NFtype_url, value = NFvalue}, _) ->
    #'google.protobuf.Any'{type_url =
                               if NFtype_url =:= undefined -> PFtype_url;
                                  true -> NFtype_url
                               end,
                           value =
                               if NFvalue =:= undefined -> PFvalue;
                                  true -> NFvalue
                               end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'google.rpc.Status' -> 'v_msg_google.rpc.Status'(Msg, [MsgName], TrUserData);
        'google.protobuf.Any' -> 'v_msg_google.protobuf.Any'(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,'v_msg_google.rpc.Status'/3}).
-dialyzer({nowarn_function,'v_msg_google.rpc.Status'/3}).
'v_msg_google.rpc.Status'(#'google.rpc.Status'{code = F1, message = F2, details = F3}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> 'v_enum_google.rpc.Code'(F1, [code | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [message | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> 'v_msg_google.protobuf.Any'(F3, [details | Path], TrUserData)
    end,
    ok;
'v_msg_google.rpc.Status'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'google.rpc.Status'}, X, Path).

-compile({nowarn_unused_function,'v_msg_google.protobuf.Any'/3}).
-dialyzer({nowarn_function,'v_msg_google.protobuf.Any'/3}).
'v_msg_google.protobuf.Any'(#'google.protobuf.Any'{type_url = F1, value = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [type_url | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_bytes(F2, [value | Path], TrUserData)
    end,
    ok;
'v_msg_google.protobuf.Any'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'google.protobuf.Any'}, X, Path).

-compile({nowarn_unused_function,'v_enum_google.rpc.Code'/3}).
-dialyzer({nowarn_function,'v_enum_google.rpc.Code'/3}).
'v_enum_google.rpc.Code'('OK', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('CANCELLED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('UNKNOWN', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('INVALID_ARGUMENT', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('DEADLINE_EXCEEDED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('NOT_FOUND', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('ALREADY_EXISTS', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('PERMISSION_DENIED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('UNAUTHENTICATED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('RESOURCE_EXHAUSTED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('FAILED_PRECONDITION', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('ABORTED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('OUT_OF_RANGE', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('UNIMPLEMENTED', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('INTERNAL', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('UNAVAILABLE', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'('DATA_LOSS', _Path, _TrUserData) -> ok;
'v_enum_google.rpc.Code'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_google.rpc.Code'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'google.rpc.Code'}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,v_type_bytes/3}).
-dialyzer({nowarn_function,v_type_bytes/3}).
v_type_bytes(B, _Path, _TrUserData) when is_binary(B) -> ok;
v_type_bytes(B, _Path, _TrUserData) when is_list(B) -> ok;
v_type_bytes(X, Path, _TrUserData) -> mk_type_error(bad_binary_value, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'google.rpc.Code'},
      [{'OK', 0},
       {'CANCELLED', 1},
       {'UNKNOWN', 2},
       {'INVALID_ARGUMENT', 3},
       {'DEADLINE_EXCEEDED', 4},
       {'NOT_FOUND', 5},
       {'ALREADY_EXISTS', 6},
       {'PERMISSION_DENIED', 7},
       {'UNAUTHENTICATED', 16},
       {'RESOURCE_EXHAUSTED', 8},
       {'FAILED_PRECONDITION', 9},
       {'ABORTED', 10},
       {'OUT_OF_RANGE', 11},
       {'UNIMPLEMENTED', 12},
       {'INTERNAL', 13},
       {'UNAVAILABLE', 14},
       {'DATA_LOSS', 15}]},
     {{msg, 'google.rpc.Status'},
      [#field{name = code, fnum = 1, rnum = 2, type = {enum, 'google.rpc.Code'}, occurrence = optional, opts = []},
       #field{name = message, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
       #field{name = details, fnum = 3, rnum = 4, type = {msg, 'google.protobuf.Any'}, occurrence = optional, opts = []}]},
     {{msg, 'google.protobuf.Any'}, [#field{name = type_url, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = value, fnum = 2, rnum = 3, type = bytes, occurrence = optional, opts = []}]}].


get_msg_names() -> ['google.rpc.Status', 'google.protobuf.Any'].


get_group_names() -> [].


get_msg_or_group_names() -> ['google.rpc.Status', 'google.protobuf.Any'].


get_enum_names() -> ['google.rpc.Code'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
        Es when is_list(Es) -> Es;
        error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def('google.rpc.Status') ->
    [#field{name = code, fnum = 1, rnum = 2, type = {enum, 'google.rpc.Code'}, occurrence = optional, opts = []},
     #field{name = message, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
     #field{name = details, fnum = 3, rnum = 4, type = {msg, 'google.protobuf.Any'}, occurrence = optional, opts = []}];
find_msg_def('google.protobuf.Any') -> [#field{name = type_url, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = value, fnum = 2, rnum = 3, type = bytes, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def('google.rpc.Code') ->
    [{'OK', 0},
     {'CANCELLED', 1},
     {'UNKNOWN', 2},
     {'INVALID_ARGUMENT', 3},
     {'DEADLINE_EXCEEDED', 4},
     {'NOT_FOUND', 5},
     {'ALREADY_EXISTS', 6},
     {'PERMISSION_DENIED', 7},
     {'UNAUTHENTICATED', 16},
     {'RESOURCE_EXHAUSTED', 8},
     {'FAILED_PRECONDITION', 9},
     {'ABORTED', 10},
     {'OUT_OF_RANGE', 11},
     {'UNIMPLEMENTED', 12},
     {'INTERNAL', 13},
     {'UNAVAILABLE', 14},
     {'DATA_LOSS', 15}];
find_enum_def(_) -> error.


enum_symbol_by_value('google.rpc.Code', Value) -> 'enum_symbol_by_value_google.rpc.Code'(Value).


enum_value_by_symbol('google.rpc.Code', Sym) -> 'enum_value_by_symbol_google.rpc.Code'(Sym).


'enum_symbol_by_value_google.rpc.Code'(0) -> 'OK';
'enum_symbol_by_value_google.rpc.Code'(1) -> 'CANCELLED';
'enum_symbol_by_value_google.rpc.Code'(2) -> 'UNKNOWN';
'enum_symbol_by_value_google.rpc.Code'(3) -> 'INVALID_ARGUMENT';
'enum_symbol_by_value_google.rpc.Code'(4) -> 'DEADLINE_EXCEEDED';
'enum_symbol_by_value_google.rpc.Code'(5) -> 'NOT_FOUND';
'enum_symbol_by_value_google.rpc.Code'(6) -> 'ALREADY_EXISTS';
'enum_symbol_by_value_google.rpc.Code'(7) -> 'PERMISSION_DENIED';
'enum_symbol_by_value_google.rpc.Code'(16) -> 'UNAUTHENTICATED';
'enum_symbol_by_value_google.rpc.Code'(8) -> 'RESOURCE_EXHAUSTED';
'enum_symbol_by_value_google.rpc.Code'(9) -> 'FAILED_PRECONDITION';
'enum_symbol_by_value_google.rpc.Code'(10) -> 'ABORTED';
'enum_symbol_by_value_google.rpc.Code'(11) -> 'OUT_OF_RANGE';
'enum_symbol_by_value_google.rpc.Code'(12) -> 'UNIMPLEMENTED';
'enum_symbol_by_value_google.rpc.Code'(13) -> 'INTERNAL';
'enum_symbol_by_value_google.rpc.Code'(14) -> 'UNAVAILABLE';
'enum_symbol_by_value_google.rpc.Code'(15) -> 'DATA_LOSS'.


'enum_value_by_symbol_google.rpc.Code'('OK') -> 0;
'enum_value_by_symbol_google.rpc.Code'('CANCELLED') -> 1;
'enum_value_by_symbol_google.rpc.Code'('UNKNOWN') -> 2;
'enum_value_by_symbol_google.rpc.Code'('INVALID_ARGUMENT') -> 3;
'enum_value_by_symbol_google.rpc.Code'('DEADLINE_EXCEEDED') -> 4;
'enum_value_by_symbol_google.rpc.Code'('NOT_FOUND') -> 5;
'enum_value_by_symbol_google.rpc.Code'('ALREADY_EXISTS') -> 6;
'enum_value_by_symbol_google.rpc.Code'('PERMISSION_DENIED') -> 7;
'enum_value_by_symbol_google.rpc.Code'('UNAUTHENTICATED') -> 16;
'enum_value_by_symbol_google.rpc.Code'('RESOURCE_EXHAUSTED') -> 8;
'enum_value_by_symbol_google.rpc.Code'('FAILED_PRECONDITION') -> 9;
'enum_value_by_symbol_google.rpc.Code'('ABORTED') -> 10;
'enum_value_by_symbol_google.rpc.Code'('OUT_OF_RANGE') -> 11;
'enum_value_by_symbol_google.rpc.Code'('UNIMPLEMENTED') -> 12;
'enum_value_by_symbol_google.rpc.Code'('INTERNAL') -> 13;
'enum_value_by_symbol_google.rpc.Code'('UNAVAILABLE') -> 14;
'enum_value_by_symbol_google.rpc.Code'('DATA_LOSS') -> 15.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"google.rpc.Status">>) -> 'google.rpc.Status';
fqbin_to_msg_name(<<"google.protobuf.Any">>) -> 'google.protobuf.Any';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('google.rpc.Status') -> <<"google.rpc.Status">>;
msg_name_to_fqbin('google.protobuf.Any') -> <<"google.protobuf.Any">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"google.rpc.Code">>) -> 'google.rpc.Code';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('google.rpc.Code') -> <<"google.rpc.Code">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'google.rpc'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "status.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["status.proto", "any.proto", "code.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["status", "any", "code"].


get_msg_containment("status") -> ['google.rpc.Status'];
get_msg_containment("any") -> ['google.protobuf.Any'];
get_msg_containment("code") -> [];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("status") -> 'google.rpc';
get_pkg_containment("any") -> 'google.protobuf';
get_pkg_containment("code") -> 'google.rpc';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("status") -> [];
get_service_containment("any") -> [];
get_service_containment("code") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("status") -> [];
get_rpc_containment("any") -> [];
get_rpc_containment("code") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("status") -> [];
get_enum_containment("any") -> [];
get_enum_containment("code") -> ['google.rpc.Code'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"google.rpc.Status">>) -> "status";
get_proto_by_msg_name_as_fqbin(<<"google.protobuf.Any">>) -> "any";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"google.rpc.Code">>) -> "code";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"google.rpc">>) -> ["code", "status"];
get_protos_by_pkg_name_as_fqbin(<<"google.protobuf">>) -> ["any"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.18.0".

gpb_version_as_list() ->
    [4,18,0].

gpb_version_source() ->
    "file".
