%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(spear_proto_code).
-define(spear_proto_code, true).

-define(spear_proto_code_gpb_version, "4.18.0").


-endif.
