%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.17.0

-ifndef(users).
-define(users, true).

-define(users_gpb_version, "4.17.0").

-ifndef('EVENT_STORE.CLIENT.USERS.CREATEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CREATEREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.CreateReq.Options',
        {login_name = []        :: unicode:chardata() | undefined, % = 1, optional
         password = []          :: unicode:chardata() | undefined, % = 2, optional
         full_name = []         :: unicode:chardata() | undefined, % = 3, optional
         groups = []            :: [unicode:chardata()] | undefined % = 4, repeated
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.CREATEREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CREATEREQ_PB_H', true).
-record('event_store.client.users.CreateReq',
        {options = undefined    :: users:'event_store.client.users.CreateReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.CREATERESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CREATERESP_PB_H', true).
-record('event_store.client.users.CreateResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.UPDATEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.UPDATEREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.UpdateReq.Options',
        {login_name = []        :: unicode:chardata() | undefined, % = 1, optional
         password = []          :: unicode:chardata() | undefined, % = 2, optional
         full_name = []         :: unicode:chardata() | undefined, % = 3, optional
         groups = []            :: [unicode:chardata()] | undefined % = 4, repeated
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.UPDATEREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.UPDATEREQ_PB_H', true).
-record('event_store.client.users.UpdateReq',
        {options = undefined    :: users:'event_store.client.users.UpdateReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.UPDATERESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.UPDATERESP_PB_H', true).
-record('event_store.client.users.UpdateResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DELETEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DELETEREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.DeleteReq.Options',
        {login_name = []        :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DELETEREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DELETEREQ_PB_H', true).
-record('event_store.client.users.DeleteReq',
        {options = undefined    :: users:'event_store.client.users.DeleteReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DELETERESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DELETERESP_PB_H', true).
-record('event_store.client.users.DeleteResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.ENABLEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.ENABLEREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.EnableReq.Options',
        {login_name = []        :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.ENABLEREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.ENABLEREQ_PB_H', true).
-record('event_store.client.users.EnableReq',
        {options = undefined    :: users:'event_store.client.users.EnableReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.ENABLERESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.ENABLERESP_PB_H', true).
-record('event_store.client.users.EnableResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DISABLEREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DISABLEREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.DisableReq.Options',
        {login_name = []        :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DISABLEREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DISABLEREQ_PB_H', true).
-record('event_store.client.users.DisableReq',
        {options = undefined    :: users:'event_store.client.users.DisableReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DISABLERESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DISABLERESP_PB_H', true).
-record('event_store.client.users.DisableResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DETAILSREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DETAILSREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.DetailsReq.Options',
        {login_name = []        :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DETAILSREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DETAILSREQ_PB_H', true).
-record('event_store.client.users.DetailsReq',
        {options = undefined    :: users:'event_store.client.users.DetailsReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DETAILSRESP.USERDETAILS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DETAILSRESP.USERDETAILS_PB_H', true).
-record('event_store.client.users.DetailsResp.UserDetails',
        {login_name = []        :: unicode:chardata() | undefined, % = 1, optional
         full_name = []         :: unicode:chardata() | undefined, % = 2, optional
         groups = []            :: [unicode:chardata()] | undefined, % = 3, repeated
         last_updated = undefined :: users:'event_store.client.users.DetailsResp.UserDetails.DateTime'() | undefined, % = 4, optional
         disabled = false       :: boolean() | 0 | 1 | undefined % = 5, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DETAILSRESP.USERDETAILS.DATETIME_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DETAILSRESP.USERDETAILS.DATETIME_PB_H', true).
-record('event_store.client.users.DetailsResp.UserDetails.DateTime',
        {ticks_since_epoch = 0  :: integer() | undefined % = 1, optional, 64 bits
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.DETAILSRESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.DETAILSRESP_PB_H', true).
-record('event_store.client.users.DetailsResp',
        {user_details = undefined :: users:'event_store.client.users.DetailsResp.UserDetails'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.ChangePasswordReq.Options',
        {login_name = []        :: unicode:chardata() | undefined, % = 1, optional
         current_password = []  :: unicode:chardata() | undefined, % = 2, optional
         new_password = []      :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDREQ_PB_H', true).
-record('event_store.client.users.ChangePasswordReq',
        {options = undefined    :: users:'event_store.client.users.ChangePasswordReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDRESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.CHANGEPASSWORDRESP_PB_H', true).
-record('event_store.client.users.ChangePasswordResp',
        {
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.RESETPASSWORDREQ.OPTIONS_PB_H').
-define('EVENT_STORE.CLIENT.USERS.RESETPASSWORDREQ.OPTIONS_PB_H', true).
-record('event_store.client.users.ResetPasswordReq.Options',
        {login_name = []        :: unicode:chardata() | undefined, % = 1, optional
         new_password = []      :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.RESETPASSWORDREQ_PB_H').
-define('EVENT_STORE.CLIENT.USERS.RESETPASSWORDREQ_PB_H', true).
-record('event_store.client.users.ResetPasswordReq',
        {options = undefined    :: users:'event_store.client.users.ResetPasswordReq.Options'() | undefined % = 1, optional
        }).
-endif.

-ifndef('EVENT_STORE.CLIENT.USERS.RESETPASSWORDRESP_PB_H').
-define('EVENT_STORE.CLIENT.USERS.RESETPASSWORDRESP_PB_H', true).
-record('event_store.client.users.ResetPasswordResp',
        {
        }).
-endif.

-endif.
